### ISSUE TITLE
Error changing animations

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [mrgoonie/flutter_universal_widget#3]
When running the example doing a yoyo motion animation and clicking the change color animation, it doesn't change color. It just stops and starts the widget.

**Comment by mrgoonie** [comment]
Thanks for pointing out this @ThinkDigitalRepair, I've fixed the issue and commit new code, also published the new package version at https://pub.dartlang.org/packages/universal_widget. Would you mind to check again to see if the issue was fixed on your side? 

Thanks.

**Comment by ThinkDigitalRepair** [comment]
Yes, this has been fixed. Thanks!
