### ISSUE TITLE
opacity:1.0 works but opacity:0.0 works on the second time

### ISSUE THREAD

**Issue by aytunch** [mrgoonie/flutter_universal_widget#4]
`UniversalWidget.find("key").update(duration: 1.8, opacity: 1.0);`
Always work but,

`UniversalWidget.find("key").update(duration: 1.8, opacity: 0.0);`

This works mostly in the second time I press the button. Is this an issue or am I doing something wrong?

**Comment by mrgoonie** [comment]
That sounds like a bug, let me check.

**Comment by mrgoonie** [comment]
Hmm... it seems to work as expected, I've just add into the example in this commit: https://github.com/mrgoonie/flutter_universal_widget/commit/aa5a5285c806bbab288fd109e6b0ab0d5ea5df0a#diff-2eaa04528257122bb1569969077bda62

Can you check again?

![Screen-Recording-2019-03-22-at-2 20](https://user-images.githubusercontent.com/6857382/54806954-4066a500-4cae-11e9-83bd-7fd902f67ab6.gif)

**Comment by aytunch** [comment]
this was caused by another plugin i guess. Now the problem disappeared. thanks for the info
